#define IDC_RSCDISPLAYARSENAL_TAB_CARGOBULLET 27
#define AMMO_TRANSLATION_TABLE \
    private ammotypes = createHashMapFromArray [["CUP_B_545x39_Ball", "B_545x39_Ball_F"],\
    ["CUP_B_545x39_Ball_Tracer_Green", "B_545x39_Ball_Green_F"],\
    ["CUP_B_762x39_Ball", "B_762x39_Ball_F"],\
    ["CUP_B_762x39_Ball_Tracer_Green", "B_762x39_Ball_Green_F" ],\
    ["CUP_B_762x51_noTracer", "B_762x51_Ball"],\
    ["CUP_B_762x51_Tracer_Green","B_762x51_Tracer_Green"],\
    ["CUP_B_762x51_Red_Tracer_3RndBurst","B_762x51_Tracer_Red"],\
    ["CUP_B_762x51_Tracer_Red_Splash","B_762x51_Tracer_Red"],\
    ["CUP_B_762x51_Tracer_Red","B_762x51_Tracer_Red"],\
    ["CUP_B_762x51_Tracer_Yellow", "B_762x51_Tracer_Yellow"],\
    ["CUP_B_762x54_Ball_Green_Tracer","B_762x54_Tracer_Green"],\
    ["CUP_B_762x54_Ball_Red_Tracer","B_762x54_Tracer_Red"],\
    ["CUP_B_762x54_Ball_Yellow_Tracer","B_762x54_Tracer_Yellow"]];