		class riflesMCX 
		{
			displayName = "Sig MCX Spear";
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\primaryWeapon_ca.paa";

			ITEM(KAR_XM7, MOD762, RIFLE_STOCK);
			ITEM(KAR_XM7_BLK, MOD762, RIFLE_STOCK);
			ITEM(KAR_XM7_G, MODGL762, RIFLE_STOCK);
			ITEM(KAR_XM7_BLK_G, MODGL762, RIFLE_STOCK);
			
			ITEM(KAR_20Rnd_Fury, 20 + BULPRICE*20, MAGAZINE_STOCK);
			ITEM(KAR_20Rnd_Fury_blk, 20 + BULPRICE*20, MAGAZINE_STOCK);
			ITEM(KAR_20Rnd_Fury_GT, 20 + BULPRICE*20, MAGAZINE_STOCK);
			ITEM(KAR_20Rnd_Fury_GT_blk, 20 + BULPRICE*20, MAGAZINE_STOCK);
			ITEM(KAR_20Rnd_Fury_RT, 20 + BULPRICE*20, MAGAZINE_STOCK);
			ITEM(KAR_20Rnd_Fury_RT_blk, 20 + BULPRICE*20, MAGAZINE_STOCK);
			ITEM(KAR_20Rnd_Fury_YT, 20 + BULPRICE*20, MAGAZINE_STOCK);
			ITEM(KAR_20Rnd_Fury_YT_blk, 20 + BULPRICE*20, MAGAZINE_STOCK);
		};
